spring.application.name=EurekaServer

server.port=${EUREKA_SERVER_PORT}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER_ID}:${EUREKA_SERVER_PASSWORD}@${EUREKA_SERVER_IP}:${EUREKA_SERVER_PORT}/eureka

eureka.username=${EUREKA_SERVER_ID}
eureka.password=${EUREKA_SERVER_PASSWORD}