spring:
  application:
    name: api-gateway
  profiles:
    active: dev
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: health-check
#              uri: lb://msaTest
#              predicates:
#                - Path=/health-check/**
#      server:
#        webmvc:
#          routes:
#            - id: health-check
#              uri: http://localhost:8080
#              predicates:
#                - Path=/health-check/**

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_ID}:${EUREKA_SERVER_PASSWORD}@${EUREKA_SERVER_IP}:${EUREKA_SERVER_PORT}/eureka

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: gateway

actuator:
  id: ${ACTUATOR_ID}
  password: ${ACTUATOR_PASSWORD}